/**
 * Hook for parallel follow-up generation using dedicated model
 *
 * This hook manages the generation of follow-up suggestions using a dedicated
 * fast/cheap model in parallel with (or after) the main AI response.
 */

import { useState, useEffect, useCallback } from 'react'
import type { Message, CategorizedFollowUp } from '@/types'

interface UseDedicatedFollowUpsOptions {
  enabled: boolean // Whether to use dedicated follow-up model
  model?: string // Custom model (optional)
  apiKey: string // OpenRouter API key
}

interface FollowUpState {
  followUps: CategorizedFollowUp[]
  isGenerating: boolean
  error: string | null
  source: 'dedicated-model' | 'fallback-templates' | 'inline' | null
}

/**
 * Generate follow-ups using dedicated background model
 */
export function useDedicatedFollowUps(
  messages: Message[],
  options: UseDedicatedFollowUpsOptions
): FollowUpState & { generateFollowUps: () => Promise<void> } {
  const [state, setState] = useState<FollowUpState>({
    followUps: [],
    isGenerating: false,
    error: null,
    source: null,
  })

  const generateFollowUps = useCallback(async () => {
    if (!options.enabled || !options.apiKey || messages.length === 0) {
      return
    }

    setState(prev => ({ ...prev, isGenerating: true, error: null }))

    try {
      const response = await fetch('/api/followups', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          messages,
          model: options.model,
          apiKey: options.apiKey,
        }),
      })

      if (!response.ok) {
        throw new Error(`Follow-up generation failed: ${response.status}`)
      }

      const data = await response.json()

      if (data.success && data.followUps) {
        setState({
          followUps: data.followUps,
          isGenerating: false,
          error: null,
          source: data.source || 'dedicated-model',
        })
      } else {
        throw new Error('Invalid response from follow-up API')
      }
    } catch (error) {
      console.error('[useDedicatedFollowUps] Error:', error)
      setState({
        followUps: [],
        isGenerating: false,
        error: error instanceof Error ? error.message : 'Unknown error',
        source: null,
      })
    }
  }, [messages, options])

  return {
    ...state,
    generateFollowUps,
  }
}

/**
 * Inject follow-ups into message content
 * This is used to add follow-ups generated by the dedicated model
 * into the message content so they can be parsed by the standard parser
 */
export function injectFollowUpsIntoMessage(
  messageContent: string,
  followUps: CategorizedFollowUp[]
): string {
  // Group by category
  const grouped = {
    quick: followUps.filter(f => f.category === 'quick').map(f => f.text).slice(0, 2),
    deep: followUps.filter(f => f.category === 'deep').map(f => f.text).slice(0, 2),
    related: followUps.filter(f => f.category === 'related').map(f => f.text).slice(0, 2),
  }

  // Create JSON structure
  const followUpJSON = JSON.stringify(grouped, null, 2)

  // Append to message content
  return `${messageContent}\n\n[FOLLOWUP]${followUpJSON}[/FOLLOWUP]`
}

/**
 * Check if message already has follow-ups
 */
export function hasFollowUps(messageContent: string): boolean {
  return messageContent.includes('[FOLLOWUP]')
}
